sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "lts/*"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=gitdiff:ci
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
